[build]
  base = ""
  publish = "dist/"
  command = "npm start"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://atcoder-for-chinese.netlify.app"
    Access-Control-Allow-Credentials = "true"
